#!/usr/bin/env node
/**
 * P0.1 — Replace the handwritten fake TLEditorSnapshot fixture with a real
 * snapshot generated by tldraw's official store factory.
 *
 * Usage:
 *   node fix-p0-real-tldraw-test-fixture.mjs --check
 *   node fix-p0-real-tldraw-test-fixture.mjs --apply
 */

import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import process from 'node:process'

const apply = process.argv.includes('--apply')
const rootArgument = process.argv
  .slice(2)
  .find((argument) => !argument.startsWith('--'))

const root = resolve(rootArgument ?? process.cwd())

const path = resolve(
  root,
  'tests/cross-domain-contract/document-lifecycle/canvas-document-service.test.ts',
)

function fail(message) {
  console.error(`\nReal tldraw test-fixture migration failed:\n${message}\n`)
  process.exitCode = 1
}

function replaceExactlyOnce(source, oldText, newText, description) {
  const firstIndex = source.indexOf(oldText)

  if (firstIndex === -1) {
    throw new Error(
      [
        `Expected source fragment was not found: ${description}`,
        'Refusing fuzzy replacement.',
      ].join('\n'),
    )
  }

  if (source.indexOf(oldText, firstIndex + oldText.length) !== -1) {
    throw new Error(
      `Expected exactly one source fragment: ${description}`,
    )
  }

  return (
    source.slice(0, firstIndex) +
    newText +
    source.slice(firstIndex + oldText.length)
  )
}

async function main() {
  const source = await readFile(path, 'utf8')

  if (
    source.includes(
      "import { createTLStore, getSnapshot, type TLEditorSnapshot } from 'tldraw'",
    ) &&
    source.includes('return getSnapshot(createTLStore({}))')
  ) {
    console.log('The lifecycle test already uses a real tldraw snapshot fixture.')
    return
  }

  const oldImport = `import type { TLEditorSnapshot } from 'tldraw'`

  const newImport = `import {
  createTLStore,
  getSnapshot,
  type TLEditorSnapshot,
} from 'tldraw'`

  const oldFixtureBlock = `function validSnapshotWire(): TLEditorSnapshot {
  /*
   * Lifecycle tests cross the actual file parser but use a mocked editor
   * session. They must therefore provide a valid persisted snapshot envelope,
   * without pretending to reimplement live tldraw record validation.
   */
  return {
    document: {
      schema: {
        schemaVersion: 2,
        sequences: {},
      },
      store: {
        'document:document': {
          id: 'document:document',
          typeName: 'document',
          name: 'Untitled',
          meta: {},
        },
      },
    },
    session: {},
  } as TLEditorSnapshot
}

function snapshot(documentValue: unknown): TLEditorSnapshot {
  /*
   * These lifecycle tests invoke change listeners explicitly. The snapshot
   * contents are not interpreted by their mocked editor, so retain a valid
   * parser fixture instead of injecting invalid pseudo tldraw records.
   */
  void documentValue

  return validSnapshotWire()
}`

  const newFixtureBlock = `function validSnapshot(): TLEditorSnapshot {
  /*
   * Never handwrite a partial TLEditorSnapshot fixture. A snapshot includes
   * serialized store schema and session state that are owned by tldraw.
   */
  return getSnapshot(createTLStore({}))
}

function snapshot(documentValue: unknown): TLEditorSnapshot {
  /*
   * Lifecycle tests trigger their mocked editor change notification explicitly.
   * Keep their persisted value a real, tldraw-generated snapshot rather than
   * manufacturing invalid pseudo-records.
   */
  void documentValue

  return validSnapshot()
}`

  let next = replaceExactlyOnce(
    source,
    oldImport,
    newImport,
    'replace type-only tldraw import',
  )

  next = replaceExactlyOnce(
    next,
    oldFixtureBlock,
    newFixtureBlock,
    'replace handwritten TLEditorSnapshot fixture',
  )

  if (!apply) {
    console.log('Safe to replace the handwritten snapshot test fixture.')
    console.log('Run again with --apply to write the change.')
    return
  }

  await writeFile(path, next, 'utf8')

  console.log('Replaced handwritten lifecycle fixture with a real tldraw snapshot.')
  console.log('')
  console.log('Verify:')
  console.log('  pnpm --filter @hybrid-canvas/test-cross-domain-contract typecheck')
  console.log('  pnpm --filter @hybrid-canvas/test-cross-domain-contract test')
  console.log('  pnpm typecheck')
}

main().catch((error) => {
  fail(error instanceof Error ? error.message : String(error))
})