export { WorkspaceShell, type WorkspaceShellProps } from './shell/WorkspaceShell'
export { ActivityRail } from './shell/ActivityRail'
export { DocumentTabs, type DocumentTabsProps } from './shell/DocumentTabs'
export { WorkspaceSidebar } from './shell/WorkspaceSidebar'
export { NoDocumentSurface } from './empty/NoDocumentSurface'
export { InspectorHost } from './inspector/InspectorHost'
export { StatusBarHost } from './status/StatusBarHost'
export { CommandProvider, useCommands } from './commands/CommandProvider'