export { createDesktopAssetStore } from './adapters/asset/asset-store'
export { createClipboard } from './adapters/clipboard/clipboard'
export { createFileDialog } from './adapters/dialog/file-dialog'
export { createAtomicDocumentStorage } from './adapters/file/file-system'
export type { NativeRuntimeInfo } from './adapters/native-runtime-info'
export type { NativeWindow } from './adapters/native-window'
export { createExternalOpener } from './adapters/opener/external-opener'
export { createDesktopPluginVerifier } from './adapters/plugin/plugin-verifier'
export { createDesktopSettingsStore } from './adapters/settings/settings-store'
export { createSystemTheme } from './adapters/theme/system-theme'
